name: Upload Python Package

# on:
#  release:
#     types: [created]
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-sound1.2-dev
        sudo apt-get install libsdl2-2.0
        sudo apt-get install libsdl2-dev
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install pyxel pygame mido
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd muser
        python setup.py sdist bdist_wheel
        twine upload dist/*
